# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recon',
            fields=[
                ('recon_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='\u91cd\u5efaid')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='\u521b\u5efa\u7528\u6237id')),
                ('recon_progress', models.FloatField(verbose_name='\u91cd\u5efa\u8fdb\u5ea6')),
                ('image_path', models.CharField(max_length=256, verbose_name='\u56fe\u7247\u8def\u5f84')),
                ('feature_isdone', models.BooleanField(verbose_name='\u7279\u5f81\u63d0\u53d6\u662f\u5426\u5b8c\u6210')),
                ('feature_starttime', models.DateTimeField(verbose_name='\u7279\u5f81\u63d0\u53d6\u5f00\u59cb\u65f6\u95f4')),
                ('feature_endtime', models.DateTimeField(verbose_name='\u7279\u5f81\u63d0\u53d6\u7ed3\u675f\u65f6\u95f4')),
                ('feature_number', models.BigIntegerField(verbose_name='\u7279\u5f81\u70b9\u6570\u76ee')),
                ('feature_path', models.CharField(max_length=256, verbose_name='\u7279\u5f81\u70b9\u5b58\u50a8\u8def\u5f84')),
                ('matching_isdone', models.BooleanField(verbose_name='\u5339\u914d\u662f\u5426\u5b8c\u6210')),
                ('matching_starttime', models.DateTimeField(verbose_name='\u5339\u914d\u5f00\u59cb\u65f6\u95f4')),
                ('matching_endtime', models.DateTimeField(verbose_name='\u5339\u914d\u7ed3\u675f\u65f6\u95f4')),
                ('matching_number', models.BigIntegerField(verbose_name='\u5339\u914d\u6570\u76ee')),
                ('matching_path', models.CharField(max_length=256, verbose_name='\u5339\u914d\u5b58\u50a8\u8def\u5f84')),
                ('sfm_isdone', models.BooleanField(verbose_name='\u7a00\u758f\u91cd\u5efa\u662f\u5426\u5b8c\u6210')),
                ('sfm_starttime', models.DateTimeField(verbose_name='\u7a00\u758f\u91cd\u5efa\u5f00\u59cb\u65f6\u95f4')),
                ('sfm_endtime', models.DateTimeField(verbose_name='\u7a00\u758f\u91cd\u5efa\u7ed3\u675f\u65f6\u95f4')),
                ('sfm_number', models.BigIntegerField(verbose_name='\u7a00\u758f\u70b9\u6570\u76ee')),
                ('sfm_path', models.CharField(max_length=256, verbose_name='\u7a00\u758f\u91cd\u5efa\u5b58\u50a8\u8def\u5f84')),
                ('mvs_isdone', models.BooleanField(verbose_name='\u7a20\u5bc6\u91cd\u5efa\u662f\u5426\u5b8c\u6210')),
                ('mvs_starttime', models.DateTimeField(verbose_name='\u7a20\u5bc6\u91cd\u5efa\u5f00\u59cb\u65f6\u95f4')),
                ('mvs_endtime', models.DateTimeField(verbose_name='\u7a20\u5bc6\u91cd\u5efa\u7ed3\u675f\u65f6\u95f4')),
                ('mvs_number', models.BigIntegerField(verbose_name='\u7a20\u5bc6\u70b9\u6570\u76ee')),
                ('mvs_path', models.CharField(max_length=256, verbose_name='\u7a20\u5bc6\u91cd\u5efa\u5b58\u50a8\u8def\u5f84')),
                ('texture_isdone', models.BooleanField(verbose_name='\u7eb9\u7406\u91cd\u5efa\u662f\u5426\u5b8c\u6210')),
                ('texture_starttime', models.DateTimeField(verbose_name='\u7eb9\u7406\u91cd\u5efa\u5f00\u59cb\u65f6\u95f4')),
                ('texture_endtime', models.DateTimeField(verbose_name='\u7eb9\u7406\u91cd\u5efa\u7ed3\u675f\u65f6\u95f4')),
                ('texture_number', models.BigIntegerField(verbose_name='\u7eb9\u7406\u91cd\u5efa\u9762\u7247\u6570\u76ee')),
                ('texture_path', models.CharField(max_length=256, verbose_name='\u7eb9\u7406\u91cd\u5efa\u5b58\u50a8\u8def\u5f84')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['create_time'],
                'verbose_name': '\u91cd\u5efa\u4efb\u52a1',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='\u7528\u6237id')),
                ('user_type', models.SmallIntegerField(choices=[(0, '\u88ab\u5c01\u7981\u7528\u6237'), (1, '\u6b63\u5e38\u7528\u6237')], default=1, verbose_name='\u7528\u6237\u7c7b\u578b')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='\u624b\u673a\u53f7')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='\u90ae\u7bb1')),
                ('password', models.CharField(max_length=256, verbose_name='\u5bc6\u7801')),
                ('school', models.CharField(max_length=256, verbose_name='\u6240\u5728\u5b66\u6821')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['create_time'],
                'verbose_name': '\u7528\u6237',
            },
        ),
    ]
